const services = [			
    {name: "Lawn Mowing",
    icon: "mower.png",
    },
    {name: "Fertilization",
    icon: "grass.png",
    },
    {name: "Bush Shaping",
    icon: "bush.png",
    },
    {name: "Tree Trimming",
    icon: "trees.png",
    },
    {name: "Fence Building",
    icon: "fence.png",
    },
    {name: "Brick & Stone Walkways",
    icon: "brick.png",
    },       
    {name: "Power Washing",
    icon: "hose.png",
    },     
    {name: "Sprinkler Installation",
    icon: "sprinkler.png",
    },	
    {name: "Pesticide Treatment",
    icon: "pesticide.png",
    },
    {name: "Design Services",
    icon: "sketch.png",
    },					
]